#!/bin/bash

set -euo pipefail

# shellcheck source=../build-config/build.env
. "$(dirname -- "${BASH_SOURCE[0]}")/../build-config/build.env"

readonly SETUP_DIR="${REPO_ROOT}/${BB_TOP_DIR_NAME}/${BB_SETUP_DIR}"
readonly BUILD_ENV="${SETUP_DIR}/build/init-build-env"
readonly DEPLOY="${SETUP_DIR}/build/tmp/deploy/sdk"

function log() {
  echo "==> $*"
}

function die() {
  echo "ERROR: $*" >&2
  exit 1
}

function build_sdk() {
  # oe-init-build-env is not written for 'set -eu' and changes the directory.
  (
    set +eu
    # shellcheck source=/dev/null # generated by bitbake-setup, absent until prepare_env.sh runs
    . "${BUILD_ENV}" >/dev/null
    set -e
    bitbake "${BB_TARGET}" -c "${SDK_TASK}"
  )
}

function installer_name() {
  local installer
  installer="$(find "${DEPLOY}" -maxdepth 1 -name '*-toolchain*.sh' -printf '%T@ %p\n' |
    sort -rn | head -n 1 | cut -d' ' -f2-)"
  [ -n "${installer}" ] || die "no SDK installer in ${DEPLOY}"
  basename "${installer}" .sh
}

# The SDK's own metadata, deployed next to the installer, over reassembling
# machine and word size from the build configuration.
function archive_name() {
  python3 -c 'import json,sys
print("sdk-{MACHINE}-{SITEINFO_BITS}bit-{SDK_VERSION}.tar.gz".format(**json.load(open(sys.argv[1]))))' \
    "${DEPLOY}/$1.testdata.json"
}

# Run from DEPLOY instead of passing -C: the glob is expanded by the shell,
# in the current directory, before tar ever chdirs.
function pack() {
  local name="$1" archive="$2"
  (cd "${DEPLOY}" && tar -czf "${archive}" "${name}".*)
}

function main() {
  [ -f "${BUILD_ENV}" ] ||
    die "${BUILD_ENV} not found
       Set up the build first: ./scripts/prepare_env.sh"

  build_sdk

  local name archive
  name="$(installer_name)"
  mkdir -p "${SDK_DIR}"
  archive="$(cd "${SDK_DIR}" && pwd)/$(archive_name "${name}")"
  pack "${name}" "${archive}"

  log "SDK archive: ${archive} ($(du -h "${archive}" | cut -f1))"
}

main "$@"
