#!/bin/bash

set -euo pipefail

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
readonly REPO_ROOT

BB_TOP_DIR_NAME="${BB_TOP_DIR_NAME:-bitbake-builds}"
BB_SETUP_DIR="${BB_SETUP_DIR:-poky-wrynose}"
BB_TARGET="${BB_TARGET:-core-image-minimal}"
BB_MIN_FREE_GB="${BB_MIN_FREE_GB:-50}"
BB_SOURCE_OVERRIDES="${BB_SOURCE_OVERRIDES:-${REPO_ROOT}/build-config/source-overrides.json}"
BB_ROOT_LOGIN="${BB_ROOT_LOGIN:-1}"
read -ra BB_FRAGMENTS <<<"${BB_FRAGMENTS:-core/yocto/sstate-mirror-cdn}"
read -ra BB_INIT_ARGS <<<"${BB_INIT_ARGS:-poky-wrynose poky distro/poky machine/qemux86-64}"

readonly VENV_DIR="${REPO_ROOT}/bitbake-setup-venv"
readonly SETUP_DIR="${REPO_ROOT}/${BB_TOP_DIR_NAME}/${BB_SETUP_DIR}"
readonly BUILD_ENV="${SETUP_DIR}/build/init-build-env"
readonly ROOT_LOGIN_FRAGMENT="core/yocto/root-login-with-empty-password"

function log() {
  echo "==> $*"
}

function die() {
  echo "ERROR: $*" >&2
  exit 1
}

function check_build_dir() {
  local dir="${REPO_ROOT}/${BB_TOP_DIR_NAME}"
  while [ ! -d "${dir}" ]; do
    dir="$(dirname "${dir}")"
  done

  local fs free_gb
  fs="$(df -T "${dir}" | awk 'NR==2 {print $2}')"
  free_gb="$(df -BG --output=avail "${dir}" | awk 'NR==2 {gsub(/[^0-9]/, ""); print}')"

  case "${fs}" in
    9p | drvfs | cifs | smbfs | nfs | nfs4 | fuseblk)
      die "${dir} is on ${fs}: the build must live in the Linux filesystem, not on a Windows mount or a network share."
      ;;
  esac
  [ "${free_gb}" -ge "${BB_MIN_FREE_GB}" ] ||
    die "only ${free_gb} GB free in ${dir}, a clean build needs ${BB_MIN_FREE_GB} GB."

  log "Build directory: ${dir} (${fs}, ${free_gb} GB free)"
}

function install_deps() {
  sudo apt-get update
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential chrpath cpio debianutils diffstat file gawk gcc git \
    iputils-ping libacl1 libcrypt-dev locales python3 python3-git \
    python3-jinja2 python3-pexpect python3-pip python3-subunit python3-venv \
    python3-websockets socat texinfo unzip wget xz-utils zstd

  if dpkg-query -W -f='${Status}' oss4-dev 2>/dev/null | grep -q "ok installed"; then
    echo "warning: oss4-dev breaks the QEMU build, remove it with 'sudo apt remove oss4-dev'."
  fi
}

function enable_locale() {
  if ! locale --all-locales | grep -q en_US.utf8; then
    echo "en_US.UTF-8 UTF-8" | sudo tee -a /etc/locale.gen >/dev/null
    sudo locale-gen
  fi
}

function set_parallelism() {
  local cpus ram_gb threads
  cpus="$(nproc)"
  ram_gb="$(free -g | awk '/^Mem:/ {print $2}')"

  # Load is BB_NUMBER_THREADS * PARALLEL_MAKE, so cap both by 2 GB per thread.
  threads=$((ram_gb / 2 < cpus ? ram_gb / 2 : cpus))
  ((threads > 0)) || threads=1

  export BB_NUMBER_THREADS="${threads}"
  export PARALLEL_MAKE="-j${threads}"
  log "Parallelism: ${threads} threads (${cpus} CPUs, ${ram_gb} GB RAM)"
}

function bitbake_setup() {
  [ "${EUID}" -ne 0 ] || die "BitBake refuses to run as root, run this script as a normal user."

  if [ ! -x "${VENV_DIR}/bin/bitbake-setup" ]; then
    log "Creating virtual environment in ${VENV_DIR}"
    python3 -m venv "${VENV_DIR}"
  fi
  "${VENV_DIR}/bin/pip" install --quiet --upgrade pip bitbake-setup

  if [ -f "${BUILD_ENV}" ]; then
    log "Reusing the setup in ${SETUP_DIR}"
  else
    log "Initializing ${BB_INIT_ARGS[0]} in ${SETUP_DIR}"

    local pin=()
    if [ -f "${BB_SOURCE_OVERRIDES}" ]; then
      pin=(--source-overrides "${BB_SOURCE_OVERRIDES}")
      log "Pinning layer revisions from ${BB_SOURCE_OVERRIDES}"
    fi

    # Without an explicit top dir bitbake-setup takes it from its saved
    # settings or the current directory.
    "${VENV_DIR}/bin/bitbake-setup" \
      --setting default top-dir-prefix "${REPO_ROOT}" \
      --setting default top-dir-name "${BB_TOP_DIR_NAME}" \
      init --non-interactive "${pin[@]}" \
      --setup-dir-name "${BB_SETUP_DIR}" "${BB_INIT_ARGS[@]}"
    [ -f "${BUILD_ENV}" ] || die "${BUILD_ENV} not found after init."
  fi
}

function bitbake_build() {
  # oe-init-build-env is not written for 'set -eu' and changes the directory.
  (
    set +eu
    # shellcheck source=/dev/null # generated by bitbake-setup, absent until init runs
    . "${BUILD_ENV}"
    set -e
    for fragment in "${BB_FRAGMENTS[@]}"; do
      bitbake-config-build enable-fragment "${fragment}" >/dev/null
    done

    # Toggled, not just enabled: a fragment left over from a debug build
    # would otherwise stay in the image configuration unnoticed.
    if [ "${BB_ROOT_LOGIN}" != "0" ]; then
      log "Root login enabled with an empty password (BB_ROOT_LOGIN=0 to disable)"
      bitbake-config-build enable-fragment "${ROOT_LOGIN_FRAGMENT}" >/dev/null
    else
      bitbake-config-build disable-fragment "${ROOT_LOGIN_FRAGMENT}" >/dev/null
    fi
    log "Building ${BB_TARGET}"
    bitbake "${BB_TARGET}"
  )
}

function main() {
  check_build_dir
  install_deps
  enable_locale
  set_parallelism
  bitbake_setup
  bitbake_build
}

main "$@"
